apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-metrics-server-resources
rules:
  - apiGroups:
      - external.metrics.k8s.io
    resources: [ "*" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-metrics-resource-reader
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - services
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpa-controller-dynatrace-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-metrics-server-resources
subjects:
  - kind: ServiceAccount
    name: horizontal-pod-autoscaler
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-metrics-resource-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-metrics-resource-reader
subjects:
  - kind: ServiceAccount
    name: dynatrace-metrics-apiserver
    namespace: dynatrace-metric
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-metrics:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: dynatrace-metrics-apiserver
    namespace: dynatrace-metric
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynatrace-metrics-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: dynatrace-metrics-apiserver
    namespace: dynatrace-metric
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: dynatrace-metrics-apiserver
  namespace: dynatrace-metric
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dynatrace-metrics-apiserver
  name: dynatrace-metrics-apiserver
  namespace: dynatrace-metric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynatrace-metrics-apiserver
  template:
    metadata:
      labels:
        app: dynatrace-metrics-apiserver
      name: dynatrace-metrics-apiserver
    spec:
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
      serviceAccountName: dynatrace-metrics-apiserver
      containers:
        - name: dynatrace-metrics-apiserver
          image: dynatrace/dynatrace-synthetic-adapter:latest
          env:
            - name: BASE_URL
              value: "https://xmq12972.live.dynatrace.com/e/xmq12972"
          imagePullPolicy: Always
          args:
            - --secure-port=6443
            - --cert-dir=/tmp
          ports:
            - name: https
              containerPort: 6443
          volumeMounts:
            - name: temp-vol
              mountPath: /tmp
            - name: dynametric
              mountPath: /var/lib/dynatrace/secrets/dynametric
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            readOnlyRootFilesystem: true
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: [ "all" ]
      volumes:
        - name: dynametric
          secret:
            secretName: dynametric
        - name: temp-vol
          emptyDir:
            sizeLimit: 1Mi
---
apiVersion: v1
kind: Service
metadata:
  name: dynatrace-metrics-apiserver
  namespace: dynatrace-metric
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
  selector:
    app: dynatrace-metrics-apiserver
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    name: dynatrace-metrics-apiserver
    namespace: dynatrace-metric
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
